name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - name: Print current time in IST
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata
          date
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: SoupayanGhosh
      - name: Commit & Push
        run: |
          git config user.name "SoupayanGhosh"
          git config user.email "github-actions@github.com"
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
